models/brand.py
from sqlalchemy import String
from sqlalchemy.orm import mapped_column, relationship

from models import Base


class Brand(Base):
    __tablename__ = 'brand'
    logo = mapped_column(String(255), nullable=False)
    name = mapped_column(String(255), nullable=False, unique=True)
    description = mapped_column(String, nullable=False)

    manufacturers = relationship('Manufacturer', secondary='manufacturers_brands', back_populates='brands')

    def __repr__(self):
        return f'<Brand {self.name}>'

    def __str__(self):
        return self.name

models/manufacturer.py
from sqlalchemy import String
from sqlalchemy.orm import mapped_column, relationship

from models import Base


class Manufacturer(Base):
    __tablename__ = 'manufacturer'
    name = mapped_column(String(255), nullable=False, unique=True)
    description = mapped_column(String, nullable=False)
    country = mapped_column(String(255), nullable=False)
    certificates = mapped_column(String, nullable=False)

    brands = relationship('Brand', secondary='manufacturers_brands', back_populates='manufacturers')

    def __repr__(self):
        return f'<Manufacturer {self.name}>'

    def __str__(self):
        return self.name

controllers/brands.py
from flask import g
from sqlalchemy.orm import joinedload

from models import Brand
from hashlib import md5


def get_all_brands():
    brands = g.db.query(Brand).options(joinedload(Brand.manufacturers)).all()
    return brands


def get_brand(brand_id):
    brand = g.db.get(Brand, brand_id)
    return brand


def create_brand(data) -> dict:
    brand = Brand(**data)
    g.db.add(brand)
    g.db.commit()
    return brand.as_dict()


def update_brand(brand_id, data) -> dict | None:
    brand = g.db.get(Brand, brand_id)
    if not brand:
        return
    brand.update(data)
    g.db.commit()
    return brand.as_dict()


def hashed_file_name(file_name: str) -> str:
    return f"{md5(file_name.encode()).hexdigest()}.png"

controllers/manufacturers.py
from flask import g
from sqlalchemy.orm import joinedload

from models import Manufacturer


def get_all_manufacturers():
    manufacturers = g.db.query(Manufacturer).options(joinedload(Manufacturer.brands)).all()
    return manufacturers


def get_manufacturer(manufacturer_id):
    manufacturer = g.db.get(Manufacturer, manufacturer_id)
    return manufacturer


def create_manufacturer(data):
    manufacturer = Manufacturer(**data)
    g.db.add(manufacturer)
    g.db.commit()
    return manufacturer.as_dict()


def update_manufacturer(manufacturer_id, data):
    manufacturer = g.db.get(Manufacturer, manufacturer_id)
    if not manufacturer:
        return None
    manufacturer.update(data)
    g.db.commit()
    return manufacturer.as_dict()

views/client.py
from flask import Blueprint, render_template, request, Response
from PIL import Image
import json

from forms.create_brand import CreateBrandForm
from controllers.brands import get_all_brands, create_brand, hashed_file_name, get_brand
from controllers.manufacturers import get_all_manufacturers, create_manufacturer, get_manufacturer
from forms.create_manufacturer import CreateManufacturerForm

client_blueprint = Blueprint('client', __name__, url_prefix='/client')


@client_blueprint.route('/', methods=['GET'])
def index():
    return render_template('client/admin_base.html')


@client_blueprint.route('/brands', methods=['GET'])
def get_brands():
    form = CreateBrandForm(request.form)
    brands = get_all_brands()
    return render_template('client/brands.html', brands=brands, form=form)


@client_blueprint.route('/manufacturers', methods=['GET'])
def get_manufacturers():
    form = CreateManufacturerForm(request.form)
    manufacturers = get_all_manufacturers()
    return render_template('client/manufacturers.html', manufacturers=manufacturers, form=form)

templates/client/admin_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Admin | {{ model_name }}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
</head>
<body>
    {%
            set models = [
                {"url": 'client.get_brands', "name": 'Brands'},
                {"url": 'client.get_manufacturers', "name": 'Manufacturers'},
            ]
    %}
    <main class="admin d-flex p-0" style="height: 100vh">
        <div class="d-flex flex-column flex-shrink-0 p-3 bg-light" style="width: 280px">
            <a href="{{ url_for("client.index") }}" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
              <h1 class="header__logo">Admin</h1>
            </a>
            <hr>
            <ul class="nav nav-pills flex-column mb-auto">
                {% for model in models %}
                    <li class="nav-item">
                        <a href="{{ url_for(model.url) }}" class="nav-link" aria-current="page">
                        {{ model.name }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <section class="d-flex flex-column flex-shrink-0 p-3" style="width: 85%">
            <h2>{{ model_name }}</h2>
            {% block content %}{% endblock %}
        </section>
    </main>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
{% block scripts %}

{% endblock %}

</html>

templates/client/brands.html
{% extends 'client/admin_base.html' %}
{% set model_name = 'Brands' %}
{% from "_formhelper.html" import render_field %}
{% from "macroses.html" import alerts, modal %}

{% block content %}
    {{ alerts("Brand") }}

    <div>
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#Modal">
          Create
        </button>
        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Logo</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Manufacturers</th>
                </tr>
            </thead>
            <tbody>
                {% for brand in brands %}
                    <tr class="align-middle">
                        <td>{{ brand.id }}</td>
                        <td><img src="{{ url_for('static', filename='images/'+brand.logo) }}" alt="Brand Logo" style="width: 50px; height: 50px; object-fit: contain;"></td>
                        <td>{{ brand.name }}</td>
                        <td>{{ brand.description }}</td>
                        <td>
                            {% for manufacturer in brand.manufacturers %}
                                {{ manufacturer.name }} {{ ", " if not loop.last }}
                            {% endfor %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

        {% call modal("Brand") %}
            <form method=post id='create_brand_form'>
                  <dl>
                    {{ render_field(form.logo) }}
                    {{ render_field(form.name) }}
                    {{ render_field(form.description) }}
                    {{ render_field(form.manufacturers) }}
                  </dl>
              </form>
        {% endcall %}

{% endblock %}

{% block scripts %}
	<script>
        const url = "/api/v1/brands";
        const form = document.querySelector("#create_brand_form");
        const btn_save = document.querySelector("#btn_save");

        const successToast = document.getElementById('success_toast');
        const errorToast = document.getElementById('error_toast');

        async function sendData() {
          const formData = new FormData(form);

          try {
            const response = await fetch(url, {
              method: "POST",
              body: formData,
            });
            if (response.status === 201) {
              successToast.classList.remove('d-none');
              successToast.classList.add('d-block');
              setTimeout(() => {
                successToast.classList.remove('d-block');
                successToast.classList.add('d-none');
              }, 3000);
            } else {
              errorToast.classList.remove('d-none');
              errorToast.classList.add('d-block');
              setTimeout(() => {
                errorToast.classList.remove('d-block');
                errorToast.classList.add('d-none');
              }, 3000);
            }
          } catch (e) {
            console.error(e);
          }
        }

        btn_save.addEventListener("click", (event) => {
          sendData();
        });
    </script>
{% endblock %}

templates/client/manufacturers.html
{% extends 'client/admin_base.html' %}
{% set model_name = 'Manufacturers' %}
{% from "_formhelper.html" import render_field %}
{% from "macroses.html" import alerts, modal %}

{% block content %}
    {{ alerts("Manufacturer") }}

    <div>
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#Modal">
          Create
        </button>
        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Country</th>
                    <th>Certificates</th>
                    <th>Brands</th>
                </tr>
            </thead>
            <tbody>
                {% for manufacturer in manufacturers %}
                    <tr>
                        <td>{{ manufacturer.id }}</td>
                        <td>{{ manufacturer.name }}</td>
                        <td>{{ manufacturer.description }}</td>
                        <td>{{ manufacturer.country }}</td>
                        <td>{{ manufacturer.certificates }}</td>
                        <td>
                            {% for brand in manufacturer.brands %}
                                {{ brand.name }} {{ ", " if not loop.last }}
                            {% endfor %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

<!-- Modal -->
    {% call modal("Manufacturer") %}
        <form method=post id="create_manufacturer_form">
            <dl>
            {{ render_field(form.name) }}
            {{ render_field(form.description) }}
            {{ render_field(form.country) }}
            {{ render_field(form.certificates) }}
            {{ render_field(form.brands) }}
            </dl>
        </form>
    {% endcall %}
{% endblock %}

{% block scripts %}
	<script>
        const url = "/api/v1/manufacturers";
        const form = document.querySelector("#create_manufacturer_form");
        const btn_save = document.querySelector("#btn_save");

        const successToast = document.getElementById('success_toast');
        const errorToast = document.getElementById('error_toast');

        async function sendData() {
          const formData = new FormData(form);

          try {
            const response = await fetch(url, {
              method: "POST",
              body: formData,
            });
            if (response.status === 201) {
              successToast.classList.remove('d-none');
              successToast.classList.add('d-block');
              setTimeout(() => {
                successToast.classList.remove('d-block');
                successToast.classList.add('d-none');
              }, 3000);
            } else {
              errorToast.classList.remove('d-none');
              errorToast.classList.add('d-block');
              setTimeout(() => {
                errorToast.classList.remove('d-block');
                errorToast.classList.add('d-none');
              }, 3000);
            }
          } catch (e) {
            console.error(e);
          }
        }

        btn_save.addEventListener("click", (event) => {
          sendData();
        });
    </script>
{% endblock %}